//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ASPNETMVC.EF.Domain.Testing
{
	using System;
	using System.Data.Entity;
	using System.Data.Entity.Infrastructure;

public partial class FakeShopContext : IShopContext
{

	public FakeShopContext()
    {
			Orders = new FakeOrdersDbSet();
		Products = new FakeProductsDbSet();
		Users = new FakeUsersDbSet();
    }


	public IDbSet<Order> Orders { get; set; }
	public IDbSet<Product> Products { get; set; }
	public IDbSet<User> Users { get; set; }

    public int SaveChanges()
    {
        return 0;
    }

	public void SetModified(object entity)
    {
    }

    public void SetAdded(object entity)
    {
        throw new NotImplementedException();
    }

    public void Dispose()
    {
    }

}



}
	
