//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ASPNETMVC.EF.Domain.Testing
{
	using System;
	using System.Data.Entity;

	public partial class FakeOrdersDbSet : FakeDbSet<Order>
	{
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ASPNETMVC.EF.Domain.Testing
{
	using System;
	using System.Data.Entity;

	public partial class FakeProductsDbSet : FakeDbSet<Product>
	{
	}
}
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ASPNETMVC.EF.Domain.Testing
{
	using System;
	using System.Data.Entity;

	public partial class FakeUsersDbSet : FakeDbSet<User>
	{
	}
}
