        //------------------------------------------------------------------------------
        // <auto-generated>
        //    This code was generated from a template.
        //
        //    Manual changes to this file may cause unexpected behavior in your application.
        //    Manual changes to this file will be overwritten if the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------
        namespace ASPNETMVC.EF.Domain.Testing
        {
            using System;
            using System.Data.Entity;
            using System.Data.Entity.Infrastructure;
            
            public partial class ShopEntities : DbContext, IShopEntities
            {
            
            	public ShopEntities() : base("name=ShopEntities")
                {
                }
            	protected override void OnModelCreating(DbModelBuilder modelBuilder)
                {
                    throw new UnintentionalCodeFirstException();
                }
            
            	public IDbSet<Order> Orders { get; set; }
            	public IDbSet<Product> Products { get; set; }
            	public IDbSet<User> Users { get; set; }
                
            
            }
            
            
            
            }
            	
